@startuml

UrlLink "0..*" *- "   1" AppUser: < have

AppUser "1..*" - "1..*" Authority
(AppUser, Authority) .. AppUser_authority


class AppUser {
id
uid
firstName
name
email
creation_date
update_date
}

class Authority {
id
authorityLevel
}

class AppUser_authority {
app_user_id
authority_id
}


class UrlLink {
id
url_long
url_shortKey
url_password
click_number
max_click_number
expiration_date
creation_date
update_date
appUser_Id
}

enum AuthorityLevel {
ROLE_ADMIN
ROLE_USER
}

@enduml
